### ISSUE TITLE
Cannot perform pruning and quantization in the same training run

### ISSUE THREAD

**Issue by SaulAryehKohn** [Lightning-AI/lightning#11047]
## 🐛 Bug

Cannot use the `ModelPruning` and `QuantizationAwareTraining` simultaneously during training

### To Reproduce

Reproduced here: https://colab.research.google.com/drive/1ksL2TG6MqA-TnIOmbb9qOE2z_rmrzWBE?usp=sharing

### Expected behavior

There shouldn't be a reason that we can't prune and perform quantization-aware training at the same time.

### Environment

* CUDA:
	- GPU:
		- Tesla K80
	- available:         True
	- version:           11.1
* Packages:
	- numpy:             1.19.5
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.0+cu111
	- pytorch-lightning: 1.5.5
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- 
	- processor:         x86_64
	- python:            3.7.12
	- version:           #1 SMP Sat Jun 5 09:50:34 PDT 2021

### Additional context

cc @carmocca @borda

**Comment by awaelchli** [comment]
Closing this stale issue because we removed the QAT callback in #16750. As explained in the linked PR:

The QAT callback can no longer be maintained by us. It has many issues that make the callback uneffective and these can't be fixed at the moment.

Users who rely on this callback: You can stay on the Lightning 1.9.x version which gets long-term support (LTS) OR you can copy the callback code and maintain it yourself.

If someone from the community is interested in fixing and maintaining this callback, please let us know. If important issues come up that affect several users, we will prioritize fixes accordingly for the 1.9.x LTS.
