### ISSUE TITLE
Fix typing for Strategies files

### ISSUE THREAD

**Issue by daniellepintz** [Lightning-AI/lightning#11371]
## Proposed refactor

Fix typing for these files:
https://github.com/PyTorchLightning/pytorch-lightning/blob/7eab379da2fdca542849ed4ad313d0851c2271e3/pyproject.toml#L70-L84

### Motivation

As part of #7037 we want to add typing to the entire Lightning codebase.

## Additional Context
Make sure you do one PR per file.
Start by removing the file from `pyproject.toml`. To test mypy locally make sure you have it installed and then simply run `mypy`.

cc @borda @justusschock @awaelchli @akihironitta @rohitgr7

**Comment by alat-rights** [comment]
I would love to take this on. If I'm not missing any hidden complexities here, this should be done by today?

**Comment by awaelchli** [comment]
Hello
This is wonderful.

We are targeting to get some refactors and API updates in for the strategies in upcoming Lightning 1.6 release (#11643, #9932). These have priority over typing, but you are welcome to start if you want. I'm only mentioning this because there are likely going to be merge conflicts so please ping us if you need help resolving these.  

To start, I suggest to take some easy ones like single_tpu.py, single_device.py, dp, etc.

Thanks for the help
cheers

**Comment by alat-rights** [comment]
Sounds great, I'll take a look!

Excited to join the community.

All the best

**Comment by mathemusician** [comment]
Hello! Permission to make a pull request for this?

**Comment by Borda** [comment]
> Hello! Permission to make a pull request for this? @daniellepintz

you are more then welcome to do it :tada:

**Comment by carmocca** [comment]
This is done
