### ISSUE TITLE
Asynchronous checkpointing

### ISSUE THREAD

**Issue by noamsgl** [Lightning-AI/lightning#11561]
## 🚀 Feature

The idea is to enable asynchronous model checkpointing during training.

### Motivation

I'm training thousands of small identical `gpytorch` models, each one is trained for 1000 epochs on a different 1d time series sample. The training on a GPU takes ~1/4 seconds of time. Saving the model at the end takes about 1.25 seconds, and this blocks the training of the next models and wastes GPU time.

### Pitch

Checkpointing currently blocks the training process and wastes GPU time. If implemented correctly, asynchronous (non-blocking) checkpointing could offer a significant speed up over time.

### Alternatives

Perhaps this doesn't need to be built into PyTorch-Lightning and can be implemented with asyncio.
If so, I would like to see an example.

### Additional context

______________________________________________________________________

cc @borda @awaelchli @ananthsub @ninginthecloud @rohitgr7

**Comment by tchaton** [comment]
I believe you would have a process with a queue responsible to checkpoint the model weights. This could be done directly within the ModelCheckpoint.

**Comment by carmocca** [comment]
When you say "saving the model" are you referring precisely to the IO operations to save and delete? If so, we could create a IO plugin that can work asynchronously, it could be adapted from https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/plugins/io/torch_plugin.py

**Comment by noamsgl** [comment]
Yes, that's exactly what I mean.

**Comment by awaelchli** [comment]
Adding asynchronous checkpointing, like it is implemented in #13658, would have the implication that we can't guarantee access to the checkpoints anymore. For example:

```py
trainer.fit(model)
torch.load(trainer.checkpoint_callback.best_model_path)
```
Could lead to either

1) the wrong model being loaded
2) FileNotFoundError

due to the queue being processed in a side thread. This is of course a rare edge case but can't be ignored imo. One has to provide a mechanism to synchronize or lock when accessing the checkpoint this way.

**Comment by rohitgr7** [comment]
I guess 
https://github.com/Lightning-AI/lightning/blob/2bdd8e9da838d14ef8d965debe07109462edbf47/src/pytorch_lightning/utilities/cloud_io.py#L49-L52

ensures all the checkpoints are processed before we end the training?

**Comment by awaelchli** [comment]
I thought it is supposed to address the use case of @noamsgl? Perhaps the use case here can't be fully addressed.
Nonetheless, we need to be extremely careful about race conditions. The PR does not currently implement locks between checkpoint creation and deletion. This is necessary, otherwise you end up with a main process trying to remove a checkpoint while the thread is trying to overwrite the file. 

Furthermore, there are places where we can't have asynchronous checkpointing. One example is the spawn launcher who saves a temporary checkpoint before it joins in the main process. But with switching the plugin, this would have a global effect on all saving/loading mechanisms, which is not desired in this case. The specific case of spawn here could potentially be solved by passing the data through the queue directly instead of writing a checkpoint file, but that is a different discussion altogether.

**Comment by rohitgr7** [comment]
well, it partially addresses the use case here... the only place where the slowdown will happen is when training is done, to ensure all the models are saved before training ends.

> The PR does not currently implement locks between checkpoint creation and deletion. This is necessary, otherwise you end up with a main process trying to remove a checkpoint while the thread is trying to overwrite the file.

that's why added an info message.. this is entirely optional.. user needs to know the side effects.

> Furthermore, there are places where we can't have asynchronous checkpointing. One example is the spawn launcher who saves a temporary checkpoint before it joins in the main process. But with switching the plugin, this would have a global effect on all saving/loading mechanisms, which is not desired in this case. The specific case of spawn here could potentially be solved by passing the data through the queue directly instead of writing a checkpoint file, but that is a different discussion altogether.

interesting.
