### ISSUE TITLE
What does `overfit_batches` do in trainer?

### ISSUE THREAD

**Issue by lihui-w** [Lightning-AI/lightning#12668]
I have train a model and when I evaluate it by this
```
model = LitModel()  # LightningModule
model.eval()
data = DataSet()  # LightningDataModule
trainer = pl.Trainer(gpus=[1],
    precision=16,
    overfit_batches=10,
)
trainer.validate(model,data,ckpt_path='mysave.ckpt')
```
I found the answer is bad. After debug for my code. I think it may caused by parameters `overfit_batches`.
Because I train my model by using `overfit_batches=10`. Then the answer is very different.

And in the case, I have using by two cases, the first is 
```
model = LitModel()  # LightningModule
model.eval()
data = DataSet()  # LightningDataModule
trainer = pl.Trainer(gpus=[1],
    precision=16,
)
trainer.validate(model,data,ckpt_path='mysave.ckpt')
```
And the answer is:
![1649408183(1)](https://user-images.githubusercontent.com/21123272/162401952-7e5b4537-c68e-4c63-8697-426879b50630.jpg)

In the second< I try:
```
model = LitModel()  # LightningModule
model.eval()
data = DataSet()  # LightningDataModule
trainer = pl.Trainer(gpus=[1],
    precision=16,
    overfit_batches=10,  # this is new
)
trainer.validate(model,data,ckpt_path='mysave.ckpt')
```
Then I got a difference:
![1649408425(1)](https://user-images.githubusercontent.com/21123272/162403140-695e34f6-d431-4d40-bcf8-59575e7ec60b.png)
The trainer reload data, and the batch_size is different.

And what did `overfit_batched` do in trainer? 

cc @justusschock @kaushikb11 @awaelchli @borda @rohitgr7

**Comment by awaelchli** [comment]
Hello @lihui-w 
Which version of Lightning are you using here?

The warning you are seeing is caused by calling self.log() with an element where it is ambiguous to extract the batch size. It might be that the batch size you are seeing is wrong because it couldn't be extracted properly. However, there were changes and fixes regarding that behavior in recent PL versions (cc @rohitgr7 I believe) which is why it would be good to know which version you are working with. And if you could provide a minimal reproducible script, that would be even more helpful.
