### ISSUE TITLE
MLFlow logger does not provide artifact_location for checkpointing

### ISSUE THREAD

**Issue by pimdh** [Lightning-AI/lightning#12855]
## 🐛 Bug

When using the MLFlow logger, neither the `artifact_location`, nor the `save_dir` arguments are used to resolve the checkpoint dir in `ModelCheckpoint.__resolve_ckpt_dir`, because `mlflow_logger.save_dir` always returns `None`.

### To Reproduce
```
logger = MLFlowLogger(tracking_uri=tracking_uri, artifact_location=artifact_location)
trainer = pl.Trainer(logger=logger)
trainer.checkpoint_callback.dirpath is None
```

### Expected behavior
We expect `trainer.checkpoint_callback.dirpath == artifact_location`.

### Environment
* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 2080 Ti
        - available:         True
        - version:           11.1
* Packages:
        - numpy:             1.21.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.10.2
        - pytorch-lightning: 1.6.0
        - tqdm:              4.62.2
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10
        - version:           #109~18.04.1-Ubuntu SMP Thu Jan 13 15:06:26 UTC 2022

**Comment by carmocca** [comment]
Hi @pimdh! Would you be interested in contributing this fix?

**Comment by pimdh** [comment]
Hi,
I found that the above suggestion doesn't actually lead to the correct folder being used, as the checkpoint dir resolver doesn't use the same subdir as MLFlow. The correct way of setting the directory is something like:
```python
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.loggers import MLFlowLogger
from mlflow.tracking.artifact_utils import get_artifact_uri

logger = MLFlowLogger(
    experiment_name=exp_name,
    run_name=run_name,
    tracking_uri=tracking_uri,
    artifact_location=artifact_location,
)
artifact_dir = get_artifact_uri(
    run_id=logger.run_id, tracking_uri=tracking_uri
)
checkpoint_callback = ModelCheckpoint(
    dirpath=Path(artifact_dir) / 'checkpoints'
)
```

However, if we'd set this run-specific `artifact_dir` as `logger.save_dir`, then `ModelCheckpoint.__resolve_ckpt_dir` will add a run-specific subdirectory to this:
```python
 ckpt_path = os.path.join(save_dir, str(name), version, "checkpoints")
 ```

Somehow we'd need to make clear to `__resolve_ckpt_dir` that the `save_dir` is already run-specific. Any suggestions on how to deal with this elegantly?

**Comment by carmocca** [comment]
If i'm not mistaken, you should not pass the dirpath to `ModelCheckpoint` so it uses the logger's `save_dir`: https://github.com/PyTorchLightning/pytorch-lightning/blob/55b3bc3e362c3bbd37ccf7755c4bc52c2f4c9787/pytorch_lightning/callbacks/model_checkpoint.py#L593

Which in the case of MLFlow, it's based off your `tracking_uri`: https://github.com/PyTorchLightning/pytorch-lightning/blob/55b3bc3e362c3bbd37ccf7755c4bc52c2f4c9787/pytorch_lightning/loggers/mlflow.py#L97-L99 https://github.com/PyTorchLightning/pytorch-lightning/blob/55b3bc3e362c3bbd37ccf7755c4bc52c2f4c9787/pytorch_lightning/loggers/mlflow.py#L252-L261

Note that the directory resolution is only done at run-time, concretely in the `setup` hook:
https://github.com/PyTorchLightning/pytorch-lightning/blob/55b3bc3e362c3bbd37ccf7755c4bc52c2f4c9787/pytorch_lightning/callbacks/model_checkpoint.py#L256-L257

which is why the assertion in your repro code fails.

**Comment by pimdh** [comment]
Sorry I wasn't completely clear. I'm using a SQLite DB as tracking URI. Then you can supply a directory do MLFlow to store the file artifacts in. In this case, the assertion fails.

What I meant in my second post is that in that case, MLFlow uses the following path to store the artifacts for a run:
```ARTIFACT_LOCATION/MLFLOW_RUN_ID/artifacts/```
while `__resolve_ckpt_dir` picks:
```SAVE_DIR/MLFLOW_EXPERIMENT_ID/MLFLOW_RUN_ID```

If we were to modify the `MLFlowLogger` so that the `SAVE_DIR=ARTIFACT_LOCATION`, the resolved location would still not coincide with the MLFlow artifact location and the checkpoints don't show up in the MLFlow UI.

It think that solving this would require changes in `__resolve_ckpt_dir`. Would that be okay with you? We could, for example have the loggers optionally provide the exact dir for the run logs.
