### ISSUE TITLE
PyTorch 1.12 changes default fp32 math to be "highest precision"

### ISSUE THREAD

**Issue by Borda** [Lightning-AI/lightning#12997]
In PyTorch 1.12 the default FP32 mode is moving to "highest". This is for numerical stability and the motivation can be seen here: https://github.com/pytorch/pytorch/pull/76509

The issue with this is that users who are using Ampere based GPUs are automatically using TF32 under the hood, which comes with a speed benefit for users that can work within TF32. By swapping this to default off, users who are using Ampere GPUs will not use TF32 unless they enable the flags themselves.

## Proposed refactor

The user is easily able to change the matrix multiplication precision level (highest/high/medium). 
If we detect an ampere supported card, we should warn the user that TF32 is off by default, and can be enabled through the Trainer.

cc @borda @akihironitta

**Comment by ananthsub** [comment]
> If we detect an ampere supported card, we should warn the user that TF32 is off by default, and can be enabled through the Trainer.

Why does this need to be enabled through the Trainer vs setting the torch flag directly. It's a 1-line change for users either way. It could be added to the Lightning docs on performance tips

**Comment by tanmoyio** [comment]
I want to work on it @Borda

**Comment by carmocca** [comment]
> Why does this need to be enabled through the Trainer? Users could easily set the torch flag directly. Awareness of this flag can be added to the Lightning docs for performance tips

I somewhat agree, but there's precedent for this with the `benchmark=...` flag. It just sets `cudnn.benchmark=bool`.

What would be an appropriate name for this flag though? How do we not confuse users with what it does and what's the relation to `precision=...`?

I don't think this should be set together with `benchmark=...` because I could see somebody wanting one but not the other.

> Pseudo code will go something like this:

You should be setting ` torch.set_float32_matmul_precision` with the enum value as described in https://github.com/pytorch/pytorch/issues/76440

**Comment by akihironitta** [comment]
> can we directly do `torch.set_float32_matmul_precision('high')` iff ampere card detected, then we can set the warning that the precision can be changed, as the user is using ampere cards its recommended to use TF32 for optimal performance.

@tanmoyio Are you suggesting enabling TF32 by default in PL? If so, I am opposed to the suggestion due to the issues stated in [this post](https://dev-discuss.pytorch.org/t/pytorch-and-tensorfloat32/504). Even if we raised the warning, I'd still be opposed to it because users may miss the warning or may be too busy to understand it. As the description proposes, I believe we should respect the default setting in PyTorch to avoid possible confusions and "regression" reports as we've had with `benchmark=True` #12713.

**Comment by akihironitta** [comment]
@carmocca I see. Still I'm slightly for keeping the PyTorch's default setting as I'm concerned about possible confusions that users (e.g. who will compare performance between PyTorch and PL across multiple PT/PL versions) may have.

However, at the same time, I'm fine with moving forward with the suggestion, but we just need to make sure that the change will be communicated to users in the docs (via #12398) (and by raising a `PossibleUserWarning` if it's not too loud).

---

Hi @tanmoyio, sorry for the delay! Are you still interested in working on this issue?

**Comment by a897456** [comment]
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/28752526/db67b7a1-63ec-4251-ab4e-7ffeabcdc055)
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/28752526/d77be7ce-e62b-4590-a331-abf8d4be5889)
I'm sorry, I'm new to this, but is there any conflict between these two pictures? How should I set it? @carmocca

**Comment by carmocca** [comment]
No conflict, that is correct if fp32 is desired.

**Comment by a897456** [comment]
> No conflict, that is correct if fp32 is desired.

Thank you for your reply and I am very sorry to bother you again.
If fp32 is desired as in the two pictures above, and I also want to use mixed precision, is the setting in the following picture correct?
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/28752526/d417bf8f-3bdc-4a40-be3e-cacf3d4e9221)
