### ISSUE TITLE
Using TorchScript To Deploy A Pytorch_lightning Module

### ISSUE THREAD

**Issue by NguyenDuyDuc1491995** [Lightning-AI/lightning#13401]
Hi, I make a simple example and get a trouble. I can not use internet at my workplace so I write it down. If there is any writing errors, ignore them.

```python
class SimpleModel(pytorch_lightning.LightningModule):
    def __init__(self):
        super().__init__()
            self.model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=False, pretrained_backbone=False)
       def forward(self, inputs):
            outputs = self.model(inputs)
            return outputs

simpleModel = SimpleModel()
script = simpleModel.to_torchscript()
```

Run it and the trouble is: " RuntimeError, ............." .... 

Please, try it and help me.
Thanks

**Comment by akihironitta** [comment]
@NguyenDuyDuc1491995 Could you provide your complete error message?

(For future questions, please use GitHub Discussions instead of GitHub issues: https://github.com/Lightning-AI/lightning/discussions)

**Comment by NguyenDuyDuc1995** [comment]
> @NguyenDuyDuc1491995 Could you provide your complete error message?
> 
> (For future questions, please use GitHub Discussions instead of GitHub issues: https://github.com/Lightning-AI/lightning/discussions)

1. Ok, thanks. I will use GitHub Discussions next time.
2. This is my full code:

import pytorch_lightning
import torchvision 

class SimpleModel(pytorch_lightning.LightningModule):
    def __init__(self):
        super().__init__()
        self.model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=False, pretrained_backbone=False)
    def forward(self, inputs):
        outputs = self.model(inputs)
        return outputs

simpleModel = SimpleModel()
script = simpleModel.to_torchscript()

3. These are errors:
  File "e:\_01_Projects\22_2022\_01_LearningPyTorch\_11_MainProgram\_05_Test\_100_Test.py", line 13, in <module>
    script = simpleModel.to_torchscript()
  File "C:\Users\NGUYEN DUY DUC\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\NGUYEN DUY DUC\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\core\lightning.py", line 1947, in to_torchscript
    torchscript_module = torch.jit.script(self.eval(), **kwargs)
  File "C:\Users\NGUYEN DUY DUC\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\jit\_script.py", line 1265, in script
    return torch.jit._recursive.create_script_module(
  File "C:\Users\NGUYEN DUY DUC\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\jit\_recursive.py", line 454, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "C:\Users\NGUYEN DUY DUC\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\jit\_recursive.py", line 520, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "C:\Users\NGUYEN DUY DUC\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\jit\_recursive.py", line 371, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError:

forward(__torch__.torchvision.models.detection.faster_rcnn.FasterRCNN self, Tensor[] images, Dict(str, Tensor)[]? targets=None) -> ((Dict(str, Tensor), Dict(str, Tensor)[])):
Expected a value of type 'List[Tensor]' for argument 'images' but instead found type 'Tensor (inferred)'.
Inferred the value for argument 'images' to be of type 'Tensor' because it was not annotated with an explicit type.
:
  File "e:\_01_Projects\22_2022\_01_LearningPyTorch\_11_MainProgram\_05_Test\_100_Test.py", line 9
    def forward(self, inputs):
        outputs = self.model(inputs)
                  ~~~~~~~~~~ <--- HERE
        return outputs

**Comment by lantiga** [comment]
Hi @NguyenDuyDuc1491995,

you can see this towards the end of the error message: 

> Expected a value of type 'List[Tensor]' for argument 'images' but instead found type 'Tensor (inferred)'.
> Inferred the value for argument 'images' to be of type 'Tensor' because it was not annotated with an explicit type.

Essentially the `torchvision` model expects a list of tensors in input, and your `forward` function has no type signatures. Since the type of arguments is `Tensor` by default if you omit type signatures, there's a type mismatch between what your `forward` provides (`Tensor`) and what the `torchvision` model expects (`List[Tensor]`).

To fix it, just add the correct type annotation to the `images` argument of your forward function, like:

```
from typing import List

import pytorch_lightning
import torchvision
from torch import Tensor


class SimpleModel(pytorch_lightning.LightningModule):
    def __init__(self):
        super().__init__()
        self.model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=False, pretrained_backbone=False)

    def forward(self, inputs: List[Tensor]):
        outputs = self.model(inputs)
        return outputs


simpleModel = SimpleModel()
script = simpleModel.to_torchscript()
```

This runs without errors.

**Comment by NguyenDuyDuc1491995** [comment]
> Hi @NguyenDuyDuc1491995,
> 
> you can see this towards the end of the error message:
> 
> > Expected a value of type 'List[Tensor]' for argument 'images' but instead found type 'Tensor (inferred)'.
> > Inferred the value for argument 'images' to be of type 'Tensor' because it was not annotated with an explicit type.
> 
> Essentially the `torchvision` model expects a list of tensors in input, and your `forward` function has no type annotations. Since the type of arguments is `Tensor` by default if you omit type annotations, there's a type mismatch between what your `forward` provides (`Tensor`) and what the `torchvision` model expects (`List[Tensor]`).
> 
> To fix it, just add the correct type annotation to the `images` argument of your forward function, like:
> 
> ```
> from typing import List
> 
> import pytorch_lightning
> import torchvision
> from torch import Tensor
> 
> 
> class SimpleModel(pytorch_lightning.LightningModule):
>     def __init__(self):
>         super().__init__()
>         self.model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=False, pretrained_backbone=False)
> 
>     def forward(self, inputs: List[Tensor]):
>         outputs = self.model(inputs)
>         return outputs
> 
> 
> simpleModel = SimpleModel()
> script = simpleModel.to_torchscript()
> ```
> 
> This runs without errors.

Thank you.
But if I want to use an input tensor like [4,3,800,800] instead of [[1,3,800,800], [1,3,800,800], [1,3,800,800], [1,3,800,800]], how should I do?

**Comment by lantiga** [comment]
You can pass an individual `Tensor` to your `forward` and wrap it in a `List` when you pass the argument to `self.model`, this way:

```
class SimpleModel(pytorch_lightning.LightningModule):
    def __init__(self):
        super().__init__()
        self.model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=False, pretrained_backbone=False)

    def forward(self, input: Tensor):
        outputs = self.model([input])
        return outputs
```

**Comment by NguyenDuyDuc1491995** [comment]
ok. Thank you.
