### ISSUE TITLE
Setting up submodules in `setup` doesn't work correctly with DDP

### ISSUE THREAD

**Issue by kabouzeid** [Lightning-AI/lightning#14534]
## 🐛 Bug

When setting up part of the module in `setup` while using DDP, loading the checkpoint here reports unexpected keys for all submodules that are initialized in `setup`.
https://github.com/Lightning-AI/lightning/blob/fafd2546782c8d2c249c9d7546f74b416e803af7/src/pytorch_lightning/strategies/launchers/multiprocessing.py#L151

Similar to https://github.com/Lightning-AI/lightning/issues/5410

### To Reproduce

Made only two changes, marked with `### HERE ###`.

```python
import os

import torch
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer


class RandomDataset(Dataset):
    def __init__(self, size, length):
        self.len = length
        self.data = torch.randn(length, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)
    
    ### HERE ###
    def setup(self, stage):
        self.foo = torch.nn.Linear(32, 3)

    def forward(self, x):
        return self.layer(x)

    def training_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("train_loss", loss)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("valid_loss", loss)

    def test_step(self, batch, batch_idx):
        loss = self(batch).sum()
        self.log("test_loss", loss)

    def configure_optimizers(self):
        return torch.optim.SGD(self.layer.parameters(), lr=0.1)


def run():
    train_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64), batch_size=2)
    test_data = DataLoader(RandomDataset(32, 64), batch_size=2)

    model = BoringModel()
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
        ### HERE ###
        devices=2,
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)
    trainer.test(model, dataloaders=test_data)


if __name__ == "__main__":
    run()
```

### Expected behavior

Should not report any errors.

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7

**Comment by krshrimali** [comment]
Hey, @kabouzeid - Thank you for the issue! Can you try the same code, with `strategy="ddp"` in the `Trainer` class instantiation?

```python
trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        limit_test_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
        # Add strategy here
        strategy="ddp",
        ### HERE ###
        devices=2,
)
```

By default, if `devices>1`, it uses `ddp_spawn` strategy. cc: @rohitgr7 can shed more light on this :)

**Comment by awaelchli** [comment]
Yep, this is indeed an edge case we haven't thought about I guess. So the thing here is, the main process doesn't call setup(), only the worker processes do (ddp_spawn). This is the expected behavior. But in ddp spawn, when the training finishes, we want to bring the weights back to the main process, where the user can use the trained model. Then, if the main process doesn't have the same layers as the model in the worker process, we get a mismatch. We have some options:

1. User needs to call setup() manually in the main process. Not optimal, and doesn't mix well with other strategies. 
2. We only load the weights we can, and ignore the rest. We show a warning. User can't expect the full weights to be reloaded, because only a part of their model exists. 
3. Recommend user to run with ddp instead of ddp_spawn (best option imo). 

Let me know what you think.

**Comment by blakesplay** [comment]
I am currently encountering this issue, unfortunately setting up dummy layers in my main process (equivalent to calling setup in main but without cuda support) results in sigsevs in the child processes when setup is run there.  I am restricted to using ddp_notebook as I am using Jupyter to run my model, hence the need to run setup() to create GPU agnostic layers in the first place.  I would like this model to be easily run by anyone, but the large error thrown at the end of training is a little user unfriendly...

I have no issue loading up the checkpoint in another cell with a new trainer instance and testing the model, so fixing this issue is simply a quality of life improvement, I plan on just swallowing this specific error since it occurs every time.

However, I suggest allowing us to pass in a flag to the trainer of some sort to allow setting [this line](https://github.com/Lightning-AI/lightning/blob/a3258391416c8f96c05c044562f9ad7f6880733b/src/pytorch_lightning/strategies/launchers/multiprocessing.py#L149) to use the strict=False flag.  That way Jupyter-Notebook users can Trainer.fit their modules without seeing this error if they are setting up parts of their model in setup().

> ` # TODO: pass also best score
>         # load last weights
>         if worker_output.weights_path is not None:
>             ckpt = self._strategy.checkpoint_io.load_checkpoint(worker_output.weights_path)
>             trainer.lightning_module.load_state_dict(ckpt) # <----- add option for strict=false
>             self._strategy.checkpoint_io.remove_checkpoint(worker_output.weights_path)`

**Comment by vitkl** [comment]
We have exactly the same [issue](https://github.com/scverse/scvi-tools/issues/1226#issuecomment-1382652299)  (cc @adamgayoso) when using Pyro models which create all parameters (guide) during setup: https://github.com/scverse/scvi-tools/blob/3b687c029d2f8c6fb9a37f860b97b18c24614ebd/scvi/model/base/_pyromixin.py#L61-L74 .
I also don't know where the checkpoints are saved (random directory) so I don't see any way to load the trained model. 

Would be great if this is addressed using `Trainer(ddp_load_state_dict_strict=False)` option as suggested above.

**Comment by vitkl** [comment]
We have exactly the same [issue](https://github.com/scverse/scvi-tools/issues/1226#issuecomment-1382652299)  (cc @adamgayoso) when using Pyro models which create all parameters (automatic variational distribution, eg. [this guide](https://docs.pyro.ai/en/stable/infer.autoguide.html#autohierarchicalnormalmessenger)) during setup: https://github.com/scverse/scvi-tools/blob/3b687c029d2f8c6fb9a37f860b97b18c24614ebd/scvi/model/base/_pyromixin.py#L61-L74 .
I also don't know where the checkpoints are saved (random directory) so I don't see any way to load the trained model. 

Would be great if this is addressed using `Trainer(ddp_load_state_dict_strict=False)` option as suggested above - or to address this in any other way - because it will enable to easily train automatic guide Pyro models with PyTorch-Lightning (cc @fritzo).
