### ISSUE TITLE
Adjust the error message when user passes in something other than a valid dataloader

### ISSUE THREAD

**Issue by williamFalcon** [Lightning-AI/lightning#14602]
If you pass in something that is not a valid dataloader, lightning gives this error:
```bash
No `train_dataloader()` method defined. Lightning `Trainer` expects as minimum a `training_step()`, `train_dataloader()` and `configure_optimizers()` to be defined.
```
However, this is misleading because it makes you think you need to define a train_dataloader() method... the error should be something like:

```bash
.fit() received an invalid argument for train_dataloaders, you passed in a THE_BAD_TYPE, but expected GOOD_TYPES
```

https://colab.research.google.com/drive/1qtaanBqOddJ2yzZAQhgjscyCwX2C5Yzr#scrollTo=Flyi--SpvsJN

cc @tchaton @justusschock @awaelchli @borda @kaushikb11 @rohitgr7 @akihironitta

**Comment by carmocca** [comment]
The problem is that passing `fit(train_dataloader=None)` is valid code. It's how the `Trainer` is signaled to use the `train_dataloader()` method in the `LightningModule` or `LightningDataModule`. Hence the error message.

We can improve this situation by using a default sentinel value instead of `None`: `fit(train_dataloader=A_SENTINEL_VALUE)`, then when the user passes `fit(train_dataloader=my_dataloader)` and `my_dataloader is None`, we can differentiate the usage and raise an error.

However, raising an error would be a breaking change for everybody passing `None`, for example, from default values in `.yaml` configuration files. So a warning might be better.
