### ISSUE TITLE
Issues installing and running lightning in Pipenv

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#14789]
### Bug description

The original report is here (internal access only): https://linear.app/lightning-ai/issue/LAI2-8803/use-python-m-pip-in-all-examples

It seems that users who create an environment with Pipenv can't install Lightning or run apps without prefixing `python -m`. The python -m cancer is spreading to examples and documentation, but is clearly diminishing the UX for users. A real CLI shouldn't require this awkward prefix. 

### How to reproduce the bug

```python
Pending, I need to verify this. 


1. create Pipenv environment
2. pip install lightning  # fails
3. python -m pip install lightning  # works
4. lightning run app app.py  # fails
5. python -m lightning run app app.py  # works
```

### Error messages and logs

```
TODO
```

### Important info

```

#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.10):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):

```

### More info

A PR attempting to fix this (or something related) was made at launch on the old repo: https://github.com/Lightning-AI/lightning-app/pull/855

We have guides for virtualenv and conda on our beginner guide for installation. Until this issue is resolved, we should communicate that Pipenv is not supported and that support is coming soon.

**Comment by awaelchli** [comment]
Received new repro instructions from @krishnakalyan3:

```bash
conda create -n break python=3.8
conda activate break
```

requirements.txt file:

```
youtube-dl
git+https://github.com/openai/whisper
lightning
gradio
```

app.py file:

```py
import lightning as L
from lightning_app.components.serve import ServeGradio
import gradio as gr
import whisper


class LitGradio(ServeGradio):

    inputs = gr.inputs.Textbox(default='lightning', label='name input')
    outputs = gr.outputs.Textbox(label='output')
    examples = [["hello lightning"]]

    def predict(self, input_text):
        return self.model(input_text)

    def build_model(self):
        fake_model = lambda x: f"hello {x}"
        return fake_model

class RootFlow(L.LightningFlow):
    def __init__(self):
        super().__init__()
        self.lit_gradio = LitGradio()

    def run(self):
        self.lit_gradio.run()

    def configure_layout(self):
        return [{"name": "home", "content": self.lit_gradio}]

app = L.LightningApp(RootFlow())
```

Error:

```
lightning run app app.py --cloud

Your Lightning App is starting. This won't take long.
ERROR: Found an exception when loading your application from app_break.py. Please, resolve it to run your app.

Traceback (most recent call last):
  File "app_break.py", line 4, in <module>
    import whisper
ModuleNotFoundError: No module named 'whisper'
```

He reports that running with` python -m` works fine:

```

python -m lightning run app app.py --cloud
The name of the app is: vengeful-zhukovsky-8511
upload ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0%
Application is ready in the cloud
```

Despite these precise instructions, I could not reproduce on my machine :(

**Comment by krishnakalyan3** [comment]
I tested this on my personal ubuntu laptop. Perhaps this issue is using anaconda incorrectly.

**Comment by krishnakalyan3** [comment]
This is what I found in my investigation. I am using M1 mac

```
Step 1: which lightning
> /opt/homebrew/bin/lightning
Looks like homebrew cli overrides anaconda CLI
Step 2: Remove Homebrew Reference
cd /opt/homebrew/bin/
ls | grep lightning
rm lightning
rm lightning_cloud
Step 3: Things should work normally, without python -m
```

**Comment by otaj** [comment]
So, I think I figured out the problem. When you install a package, all of its entrypoints are prepended with a shebang containing absolute path to current python version used when installing such package.

This for example means that in my environment, `lightning` script, that gets installed is prepended with this line:
`#!/home/otaj/.pyenv/versions/3.10.6/envs/lightning-dev/bin/python3.10`

One solution would be to not register `lightning` as `console_script`, but as a `script` in `entry_points`, but that comes with quite a bit of its own problems (the `script` that gets installed then just gets literally only copied, so it would need to be called `lightning` and made executable and have a "better" shebang (`#!/usr/bin/env python`), but this shebang is then not multi-platform)

In general, it seems that the issue is caused by not running `lightning` in the exactly same environment where it was installed. I know @ethanwharris has been working on a workaround that would detect you are running with a different python than expected and correct it (#15434), which should be included in a fairly recent release, so we'll see, if tha tactually solves it for everyone

**Comment by awaelchli** [comment]
This issue did not occur anymore
