### ISSUE TITLE
Can't edit profile, getting "email cannot be empty." but no field to enter the email

### ISSUE THREAD

**Issue by KogaiIrina** [Lightning-AI/lightning#15227]
### Bug description

Hi! I can't edit my profile, getting "email cannot be empty." but there is no field to enter the email
![image](https://user-images.githubusercontent.com/63745301/197041516-781b83b8-8925-4e29-a52b-a4db8bb9ae06.png)

### How to reproduce the bug

```python
1. Click the Edit button
2. Try editing the profile
3. Save the edits
4. Get the error
```

### Error messages and logs

```

Unexpected error updating the user: email cannot be empty. Please, contact support@lightning.ai.

```

### Environment

Cloud

**Comment by awaelchli** [comment]
@yurijmikhalevich or @boodland would you be able to help with this one? I also noticed in the screenshot above, the error message popup wraps the text on the characters instead of the words (there in the word "Please").

**Comment by boodland** [comment]
> @yurijmikhalevich or @boodland would you be able to help with this one? I also noticed in the screenshot above, the error message popup wraps the text on the characters instead of the words (there in the word "Please").

@awaelchli seems to me that for some reason the user was created without an email and now when trying to update its details there is a validation in the BE that checks the email can't be empty, probably we have to remove that check in the BE, or investigate why the email is empty but I think this is the case for GH account login that doesn't share email details due to privacy settings @yurijmikhalevich Can you take this one as On Call ticket?

**Comment by yurijmikhalevich** [comment]
@boodland, @awaelchli, I am on it.

**Comment by awaelchli** [comment]
This is fixed in the current version, closing.
