### ISSUE TITLE
About pytorch 2.0 and pytorch-lightning

### ISSUE THREAD

**Issue by PoPdark** [Lightning-AI/lightning#15894]
Pytorch 2.0 will be released soon. I am wondering if you have the schedule to follow it? Thank you.

cc @borda

**Comment by awaelchli** [comment]
Since 2.0 is completely backward compatible with 1.13, it will just work out of the box with Lightning. In fact, you can try it today from the nightlies. Installation instructions are [here](https://pytorch.org/get-started/pytorch-2.0/#requirements).

In time, the team will add 2.0 to the CI testing suite to run all tests against it. 

Then there is the big new feature in 2.0 that allows you to compile the model with `torch.compile`. The expectation is that he users can do that directly on the LightningModule. Some tests will have to be added here.

We can't give you a concrete ETA. So far, Lightning has always released a version shortly after the stable release of each PyTorch version with updated compatibility. We intend to follow that same pattern for 2.0.

**Comment by Borda** [comment]
> Pytorch 2.0 will be released soon. I am wondering if you have the schedule to follow it?

yes we will b testing it as son as they provide some public wheels, but until their official release (March 2023) we have about 4 months :)

**Comment by lantiga** [comment]
Just FYI @PoPdark, support for passing `torch.compile` models to the Trainer just landed in Lightning master. It will be included in the upcoming patch release this week.

**Comment by lantiga** [comment]
This went out with 1.8.4 https://github.com/Lightning-AI/lightning/releases/tag/1.8.4, closing the issue

@PoPdark let me know if you have issues trying things out, remember you have to manually get the PyTorch nightlies to get `torch.compile`

**Comment by yangky11** [comment]
Does it also work out of the box if`torch.compile` is not called manually but the model is created by Lightning CLI?

**Comment by lantiga** [comment]
For now we don't have a Trainer flag (say, `compile=True`), but we may add it in the future.

So for the moment you need to do things just like the PyTorch docs say:

```python
model = MyModel()
model = torch.compile(model)

trainer = Trainer(...)
trainer.fit(model)
```

**Comment by yangky11** [comment]
Yep, I think a `compile` flag in the future would be really helpful!

**Comment by AidenDurrant** [comment]
> Yep, I think a `compile` flag in the future would be really helpful!

Any update on the compile flag?

Currently when using LightningCLI with multiple models, optimizers and schedulers i cannot compile the models in the method outlined previously:

`model = MyModel()
model = torch.compile(model)

trainer = Trainer(...)
trainer.fit(model)`

According to the CLI documentation the model is not initialised manually and explicitly passed to the CLI trainer. https://lightning.ai/docs/pytorch/stable/cli/lightning_cli_advanced_3.html#multiple-optimizers-and-schedulers 

Any advice would be great!
