### ISSUE TITLE
Faster data modules by reducing redundant calls

### ISSUE THREAD

**Issue by davidgilbertson** [Lightning-AI/lightning#16005]
### Description & Motivation

Currently, there is nothing to prevent a data module's `prepare_data()` and `setup()` methods being called multiple times.

When running a Python file as a script, this is rarely an issue. But if using a Jupyter notebook or the ['cells' feature of PyCharm](https://blog.jetbrains.com/pycharm/2018/04/pycharm-scientific-mode-with-code-cells/), it's quite common to set up the data module once at the top of the file, then run, tweak, and re-run the remainder of the code over and over again.

In this case, there is a one-to-many relationship between "prepare the data" and "fit the model".

For CIFAR10, the "prepare the data" steps take 3 seconds on a very fast SSD/CPU, which means it takes 3 seconds before training starts, performing tasks that have already been done (checking integrity, etc)

### Pitch

Keep track of what operations have already been done, and don't repeat actions that will have no effect.

My own implementation as a workaround (using the CIFAR10DataModule from bolts) is this:
```py
class CIFAR10DataModuleFast(CIFAR10DataModule):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.prepare_data_done = False
        self.setup_stages_done = set()

    def prepare_data(self):
        if not self.prepare_data_done:
            super().prepare_data()
            self.prepare_data_done = True

    def setup(self, stage):
        if stage not in self.setup_stages_done:
            super().setup(stage)
            self.setup_stages_done.add(stage)
```

This shaves off 3 seconds (for all but the first run) and it's refreshing to hit the run button and see my training epochs start _immediately_.

### Additional context

* I assume the run times for large datasets are much worse than CIFAR10.
* Maybe this is an issue for the bolts library, or maybe it makes sense for the Trainer to track this stuff - not sure.
* Maybe some people rely on this behaviour and call `prepare_data` multiple times for some reason, in which case this would be a breaking change and require the addition of a `force` argument.
* I'm sure there are complexities around multiple processes that I've not though of :)

cc @borda @justusschock @awaelchli @carmocca

**Comment by awaelchli** [comment]
@davidgilbertson A long time ago (if you need a reference let me know and I'll find the PRs) we had some logic that would track the calls of `prepare_data` and similar hooks, but it turned out to be too "magical", as it was completely hidden from the user and caused some confusion. 

What you call the workaround here is what we currently consider the recommended way, because it is completely transparent to the user what is happening.

> Maybe some people rely on this behaviour and call prepare_data multiple times for some reason,

To be clear, these are hooks. They are not really meant to be called manually by the user. They are going to be called by the Trainer at the right time and on the right process. Given your wording, I wasn't sure if you are aware of this. 

Perhaps we could consider improving the implementation of the datamodule(s) in bolts, where instead of relying on the underlying integrity checks we either adopt the pattern you presented or have just a simple check whether the data directory exists.

**Comment by carmocca** [comment]
I fully agree with Adrian. Your workaround is the expected solution, and it would be good to upstream it to the Bolts implementation.

We reverted the choice of only calling `prepare_data` once because it was too limiting for those who wanted to run it more than once, making them reach into the Trainer internals to allow it.
Whereas the other way around, the user has the control and just needs to add a simple boolean check to their implementation (just as you did!)

**Comment by davidgilbertson** [comment]
Good answers, thanks for the clarification. Agreed that 'magic' in the core is a bad idea, but that perhaps Bolts modules can afford to be a bit fancier.

@awaelchli you did indeed pick up on the fact that I'm not 100% clear on which class methods are expected to be overridden, called, or left alone. As a new user, that would actually be my #1 piece of feedback about the docs/API in general, I even saw some hooks, like `on_validation_model_eval` that have side effects, which surprised me. I'll get the hang of it eventually I'm sure, just sharing that this is a point of confusion for at least 1 person :)
