### ISSUE TITLE
Version error in for quantization config

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#16609]
### Bug description

We set the version incorrectly here for torch>=1.13:

https://github.com/Lightning-AI/lightning/blob/b36d94edabb262e3725b61246be1e5112789c8f3/src/lightning/pytorch/callbacks/quantization.py#L248-L250

The docs in PyTorch suggest that [None can be passed in](https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/ao/quantization/qconfig.py#L257-L268), but it's not actually the case and [raises an error](https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/torch/ao/quantization/qconfig.py#L311-L313).

### How to reproduce the bug

```python
# on pytorch 1.13+
Trainer(callbacks=QuantizationAwareTraining())
```

### Error messages and logs

```
AssertionError("Version number: " + str(version) + AssertionError: Version number: Nonein get_default_qat_qconfig is not supported. Version number must be 0 or 1
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @borda

**Comment by shenoynikhil** [comment]
@awaelchli I can take this up!

**Comment by rhiga2** [comment]
Hi, is this issue still open if the callback is being deprecated?

**Comment by Borda** [comment]
> Hi, is this issue still open if the callback is being deprecated?

it still is nice to get some fixes for 1.9.x aka LTS :otter:

**Comment by awaelchli** [comment]
As @Borda said, it would be possible to include a fix in our 1.9.x since this is long time supported, and there, the callback isn't yet deprecated/removed. However, I actually haven't been able to reproduce this issue, which is why I didn't move forward with this ticket. It was originally reported by a user on slack.

**Comment by rhiga2** [comment]
I can look into the issue if I'm able to reproduce it

**Comment by rhiga2** [comment]
I can't reproduce the issue, but I think I know why. The `version` param of the function `get_default_qat_qconfig` has changed from pytorch 1.11 to 1.12+. In pytorch 1.11, the function allows you to specify the version as 1 or None, but in pytorch 1.12+, the version must be 0 or 1 (despite what the code comments state). Based on the code below, 
```
model.qconfig = torch.quantization.get_default_qat_qconfig( 
     self._qconfig, version=0 if _TORCH_GREATER_EQUAL_1_12 else None 
 ) 
```
we either call `get_default_qat_qconfig` with version=None in pytorch 3.11 and below or we call `get_default_qat_qconfig` with version=0 in pytorch 3.12. Thus the only way to run into this issue is to have `_TORCH_GREATER_EQUAL_1_12` be False yet at the same time using a pytorch version 3.11 and below.
Sources 
pytorch 1.11 code: https://pytorch.org/docs/1.11/_modules/torch/ao/quantization/qconfig.html#QConfig
pytorch 1.12 code: https://pytorch.org/docs/1.12/_modules/torch/ao/quantization/qconfig.html#QConfig
pytorch 1.13 code: https://pytorch.org/docs/1.13/_modules/torch/ao/quantization/qconfig.html#QConfig

**Comment by awaelchli** [comment]
@rhiga2 Yes, I think you are right. I was confused about the same thing too when I wrote this up. 
I found the original conversation on Slack: https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1675244909673719 
Need to ask for more info.
