### ISSUE TITLE
Basic Loop has 3 abstractmethods, docs shows 2

### ISSUE THREAD

**Issue by lharri73** [Lightning-AI/lightning#16642]
### 📚 Documentation

In the docs, when creating a new loop from scratch ([here](https://pytorch-lightning.readthedocs.io/en/stable/extensions/loops.html#creating-a-new-loop-from-scratch)), it says you only need to override `done` and `advance`. In the `Loop` class, `reset` is also marked as an abstract class and must be implemented.

cc @borda @carmocca @justusschock

**Comment by awaelchli** [comment]
Hello @lharri73 
In the development branch here, these docs have already changed. We decided to remove the docs for loops because it wasn't intuitive enough how these would be used and extended by users. Would you mind sharing a little bit the use case you are trying to tackle, why you were looking at these docs? Thanks in advance
