### ISSUE TITLE
More lenient rules for allowing multiple callbacks

### ISSUE THREAD

**Issue by albertfgu** [Lightning-AI/lightning#16962]
### Description & Motivation

Currently, there is rather strict enforcement on having multiple similar callbacks. For example, I used to save two `ModelCheckpoint`s with the same `monitor` and `mode`, but one with `save_on_epoch_end=True` and one False. (The rationale is explained below as it is somewhat orthogonal to the issue.)

In earlier versions of PL this was fine; I was previously on 1.7.6 before upgrading to 1.9.3 when my code broke. The reason is that there is now a `state_key` that is a function of some of the Callback's parameters (`monitor`, `mode`, and a few others) but not the rest of the parameters. So you are no longer allowed to have callbacks that match on those 5 parameters but differ on the rest.

Another example is the issue https://github.com/Lightning-AI/lightning/issues/16848 - where a similar use case of multiple similar callbacks is now broken. Overall, the issue is that **the set of parameters in the state_key seems arbitrary** and I believe there are legitimate cases of wanting multiple callbacks that differ on a few minor parameters. Perhaps the worry was that multiple callbacks is unnecessary, but that should be up to the user unless this breaks something deeper.

I'm not sure when exactly this change was made. I'm sure there are reasons why this strict checking is enforced and would love to hear what they are, to open up a discussion.

===============

The reason for my particular two instances of `ModelCheckpoint` was that I wanted to save the last `two` checkpoints instead of last `one` checkpoint (which `save_last` gives). And the reason for this is that I wanted to make sure checkpointing was fault tolerant; I always want a recent checkpoint, but in the edge case that PL starts writing to `last.ckpt` and the program crashes for whatever reason, then the last ckpt would be corrupted (or so I was worried about). So I wanted 2 recent checkpoints. Since this isn't supported out of the box, I had a workaround that used `ModelCheckpoints`, one of which saved after training and one after validation.

### Pitch

Restore behavior allowing for duplicate (or very similar) callbacks. In other words make the `state_key` dependent on all the arguments instead of a seemingly arbitrary subset of the parameters.

cc @borda @awaelchli

**Comment by awaelchli** [comment]
The state key is made up of arguments to form an equivalence class. If the value of any of the arguments in this set changes, then this is considered a different callback. A value of an argument outside this set can be changed arbitrarily, but the callback is still considered the "same". This is important when distinguishing multiple callbacks of the same type that have different argument values. Furthermore, this association is important when reloading the state of these callbacks. 

> the set of parameters in the state_key seems arbitrary

It is not completely arbitrary. The choice was made to strike a balance between strictness when saving vs. flexibility when reloading. There are arguments of a callback, e.g. EarlyStopping(verbose=True|False), that have no impact on the actual state. Thus, this has to be excluded from the state dict. Otherwise, if the user changes this value, it wouldn't be possible to reload the state. This is the trivial example that would break given your pitch. Then there are arguments, such as the ones you mentioned, where there are pros and cons to including and excluding it from the state dict. This can of course be discussed on a case by case basis, but it is not so easy to make that decision IMO. 

To support your use case with saving the last two recent checkpoints: You can set the monitor value to global step, mode=max, and save_top_k=2.

**Comment by albertfgu** [comment]
Thanks for the response! Originally I was thinking that it made sense for every combination of arguments to define a different Callback, but the verbose example makes it more clear why one might want to change options while loading the same callback.

**Comment by awaelchli** [comment]
Thanks for studying my reply and the edge cases here. It's a dilemma! This was the best solution we could come up with, and so far nobody was able to find a better one 😞 😅

**Comment by twidatalla** [comment]
**A silly workaround I'm thinking of using to get around this is to duplicate the metric I'm monitoring with a different name, so in my training step function I have:**

self.log('train_loss', loss, on_step=True)
self.log('train_loss_2', loss, on_step=True)

**This allows me to have multiple callbacks monitoring the same underlying metric, just with different names:**

_#If we see minimal improvement (<0.05), one more epoch_
EarlyStopping(monitor="train_loss",
                                   patience = 1,
                                   divergence_threshold = 0.7,
                                   min_delta=0.05,  
                                   verbose=False, mode="min",
                                   strict = True),

_#If we see negative improvement (<0), or loss > 0.7, immediate stop_
EarlyStopping(monitor="train_loss_2",
                                   patience = 0,
                                   divergence_threshold = 0.7,              
                                   min_delta = 0,  
                                   verbose=False, mode="min",
                                   strict = True)

**Are there any unintended consequences/drawback of doing this?**

**Comment by awaelchli** [comment]
This is a good workaround. I don't see any issue with it. You may want to consider adding `self.log(..., logger=False)` for the dummy metric if you get annoyed seeing it in TensorBoard/wandb, etc.
