### ISSUE TITLE
Add `fabric.launch` to Fabric methods section

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lightning#17413]
### 📚 Documentation

`fabric.launch()` is a key method of `L.Fabric` but it's not included in https://lightning.ai/docs/fabric/stable/api/fabric_methods.html

The API reference: https://lightning.ai/docs/fabric/stable/api/generated/lightning.fabric.fabric.Fabric.html#lightning.fabric.fabric.Fabric.launch exists but is not very thorough.

The methods section would be a good place to describe the multiple `.launch()` flavors (CLI, no callable, callable) and when should each be used.
For instance, with TPUs, you need to pass a function. The CLI and putting the code after doesn't work.

cc @borda @carmocca @justusschock @awaelchli

**Comment by awaelchli** [comment]
It was not included at the time because we didn't know if it would survive. Fabric.launch is the leftover of what used to be Lite.run(). Since then, we have included the launch in several examples and docs and so far there were no objections to it. I think it is reasonable now to add it to the method list and spell out what it does. 

The guide for using it in notebooks is here: https://lightning.ai/docs/fabric/latest/fundamentals/notebooks.html?highlight=notebook
And the regular use is documented here: https://lightning.ai/docs/fabric/latest/fundamentals/launch.html#simple-launch
