### ISSUE TITLE
Will using Lightning be faster than using PyTorch?

### ISSUE THREAD

**Issue by QinHsiu** [Lightning-AI/lightning#17989]
### 📚 Documentation

Will using Lightning be faster than using Pytorch?

cc @borda

**Comment by awaelchli** [comment]
@QinHsiu In theory, Lightning can never be faster than PyTorch because it is running on PyTorch entirely. When comparing apples to apples, they will (and should) result in the same exactly. 

Of course, Lightning has a bunch of features that can be enabled with a single line of code change (e.g. enabling mixed precision in Trainer) that would take you a lot of effort otherwise in adding it to your PyTorch code. In this sense, it is much faster to iterate and try different settings, optimizations, and scale models than in PyTorch, simply because you don't have to put up with writing and maintaining boilerplate code.

I hope this comes across well in our tutorials and code examples.
