### ISSUE TITLE
How to load only the weights of the model ?

### ISSUE THREAD

**Issue by estuday** [Lightning-AI/lightning#18055]
### Bug description

i have trained a model and just want load only weights without hyperparameters.
The following code can load the model, but it has hyperparameters and cannot be used for training other tasks:
`model=Mymodel.load_from_checkpoint('/path/to/model.ckpt')`
I tried loading the model in the following way:
```
model=torch.load('/path/to/model.ckpt')
new_model=Mymodel.load_state_dict(model['state_dict'])
```
it reported the mistake:
```
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
TypeError: load_state_dict() missing 1 required positional argument: 'state_dict'
```

### What version are you seeing the problem on?

v1.6

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @awaelchli

**Comment by awaelchli** [comment]
Hi @estuday 

Here is the problem with your code:
```
model=torch.load('/path/to/model.ckpt')
new_model=Mymodel.load_state_dict(model['state_dict'])
```

This can't work because you are trying to call `load_state_dict` on a class. Also, `torch.load` doesn't return you the model instance.

Here are the docs for loading a Model from a checkpoint trained with Lightning:
https://lightning.ai/docs/pytorch/stable/common/checkpointing_basic.html#lightningmodule-from-checkpoint

In your case, that will be:
```py
model = Mymodel.load_from_checkpoint('/path/to/model.ckpt')
```
If your model also needs some hyperparameters, you can pass them in like so:

```py
model = Mymodel.load_from_checkpoint('/path/to/model.ckpt', learning_rate=0.01, ...)
```
(this is also explained on the same doc page a bit below). 

In the future, you may also want to use the `self.save_hyperparameters()` method in your LightningModule. When you train the model, it will save the hyperparameters so the next time you load the model, you don't have to pass them in again.

I hope this helps with your error.

**Comment by awaelchli** [comment]
Also, if you need more help like this in the future, we have a forum where you can ask all sort of questions like this: https://lightning.ai/forums/

**Comment by awaelchli** [comment]
@estuday Were you able to make it work?
