### ISSUE TITLE
Make CLI able to replace an entire branch

### ISSUE THREAD

**Issue by rob-hen** [Lightning-AI/lightning#18072]
### Description & Motivation

I have a yaml file `config.yaml` of the form

```
model:
     model_param1: val1
data:
      class_path: class1
      init_args:
            arg1 : val1
```

and another config file `data.yaml` of the form

```
data:
      class_path: class2
      init_args:
            arg2 : val2
```

When I use PyTorch lightning CLI to load the configs via `python train.py --config config.yaml --config data.yaml`, it keeps the args1 entry. It looks like it's not possible to remove it.

It would be great to have the option to remove an entire branch and have it reset by a new config.

cc: @mauvilsa 

cc @borda

**Comment by mauvilsa** [comment]
I think there is a need to clarify a bit exactly what is the proposal. Let me describe the current behavior. When `class_path` is changed, the existing `init_args` are kept if the new class also has that parameter, otherwise it is removed. An example is the following:

```python
# main.py

from lightning.pytorch.cli import LightningCLI
from lightning.pytorch.demos.boring_classes import BoringDataModule, BoringModel

class DataModuleA(BoringDataModule):
    def __init__(self, param: int = 1, paramA: str = "-"):
        self.param = param
        self.paramA = paramA

class DataModuleB(BoringDataModule):
    def __init__(self, param: int = 2, paramB: float = 5.6):
        self.param = param
        self.paramB = paramB

cli = LightningCLI(
    BoringModel,
    BoringDataModule,
    subclass_mode_data=True,
    run=False,
)
```

```yaml
# configA.yaml

data:
  class_path: DataModuleA
  init_args:
    param: 3
    paramA: value
```

```yaml
# configB.yaml

data:
  class_path: DataModuleB
  init_args:
    paramB: 7.8
```

The output when running the tool is currently as follows:

```shell
$ python main.py --config=configA.yaml --config=configB.yaml --print_config
...
data:
  class_path: __main__.DataModuleB
  init_args:
    param: 3
    paramB: 7.8
```

`paramA` was removed because `DataModuleB` does not define that parameter, and `param` was kept because both subclasses define it.

@rob-hen, so the proposal is to have a way to remove parameters like `param` that are defined in both classes? How would this be done? e.g., a special command line argument like

```
python main.py --config=configA.yaml --data={} --config=configB.yaml --print_config
```

**Comment by rob-hen** [comment]
I had an error while creating the yaml file. In fact, the functionality you describe is solving the issue.
