### ISSUE TITLE
Multi GPU docs reference nonexistent distributed_backend argument

### ISSUE THREAD

**Issue by tonydavis629** [Lightning-AI/lightning#18159]
### 📚 Documentation

[Multi GPU docs](https://github.com/Lightning-AI/lightning/blob/0.9.0/docs/source/multi_gpu.rst) reference `distributed_backend` as an argument to Trainer, which does not exist in the current version. 

cc @borda

**Comment by awaelchli** [comment]
Hi @tonydavis629 
You are looking at the docs for version 0.9.0 where `distributed_backend` was a flag that existed in Trainer and was since removed. You want to make sure that you are browsing the docs for the version you are using today. So for example, the docs for Lightning 2.0 (the latest) are here: https://lightning.ai/docs/pytorch/stable/

And you'll find a similar multi-GPU docs page here: https://lightning.ai/docs/pytorch/stable/accelerators/gpu.html
At the top of the docs page in the navigation header, you'll also find a button for "previous versions". 

Let me know if this helps.
