### ISSUE TITLE
Basic ProgressBar does not work

### ISSUE THREAD

**Issue by dnaihao** [Lightning-AI/lightning#18170]
### Bug description

Version of `pytorch_lightning==2.0.6`, `tqdm==4.65.0`
I want to display the training progress of my models and the basic ProgressBar from pytorch_lightning.callbacks does not work (nothing shows up).
However, when I switched to RichProgressBar, the rich progress bar shows up.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

`python
pytorch_lightning.callbacks import ProgressBar` does not show up anything.

`from pytorch_lightning.callbacks import RichProgressBar` can show the training progress.

### Error messages and logs

Nothing shows up for ```ProgressBar```.

### Environment
`pytorch_lightning==2.0.6`
`tqdm==4.65.0`

### More info
Running things in a Linux environment, with an A40 GPU.

cc @awaelchli

**Comment by awaelchli** [comment]
Hi @dnaihao 

You don't need to import the progress bar if you want to use tqdm. It gets enabled by default if you just run the Trainer :)
The reason why you don't see anything is because you accidentally imported the base class, but you probably wanted to import `pytorch_lightning.callbacks import TQDMProgressBar`. (But again, it is the default, so it's not necessary technically). 

Let me know if that resolves your problem :)

**Comment by dnaihao** [comment]
Thanks for the explanation. 
But for the previous versions of Pytorch Lightening (probably around 1.6.X), I imported ProgressBar and it worked out perfectly fine.
But sure, I am using the TODMProgressBar now and it works fine.

**Comment by awaelchli** [comment]
Yes, you are right, in previous versions prior to 2.0, ProgressBar was the tqdm-version. Later, the name of the base class was changed from ProgressBarBase to just ProgressBar #17058. Apologies if this caused confusion!
