### ISSUE TITLE
Support FSDP's hybrid-shard

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lightning#18552]
### Description & Motivation

FSDP has an option `_HYBRID_SHARD_ZERO2` that we didn't document in our guides:
https://pytorch.org/docs/stable/fsdp.html#torch.distributed.fsdp.ShardingStrategy

It is considered experimental for now, but the key difference to the other sharding strategies is that two process groups are required. The documentation states:

> process_group ([Optional](https://docs.python.org/3/library/typing.html#typing.Optional)[[Union](https://docs.python.org/3/library/typing.html#typing.Union)[ProcessGroup, [Tuple](https://docs.python.org/3/library/typing.html#typing.Tuple)[ProcessGroup, ProcessGroup]]]) – Optional[Union[ProcessGroup, Tuple[ProcessGroup, ProcessGroup]]] This is the process group used for collective communications and the one over which the model is sharded. For hybrid sharding strategies such as ShardingStrategy.HYBRID_SHARD users can pass in a tuple of process groups representing the groups to shard and replicate across, respectively.

### Pitch

1. Add the `FSDPStrategy(sharding_strategy="_HYBRID_SHARD_ZERO2")` as a string option for convenient selection by the user.
2. Handle the process group settings automatically.

### Alternatives

User has to override the strategy

### Additional context

This was brought up by a Lightning AI customer offline.

cc @borda @awaelchli @carmocca

**Comment by carmocca** [comment]
I'm looking at the internals, and the override might not be necessary if the strategy wasn't passing
https://github.com/Lightning-AI/lightning/blob/1cee84ca2d8f23ed86fbd9b0a7be8b766d39ea95/src/lightning/pytorch/strategies/fsdp.py#L286
which could be removed, alongside https://github.com/Lightning-AI/lightning/blob/1cee84ca2d8f23ed86fbd9b0a7be8b766d39ea95/src/lightning/pytorch/strategies/fsdp.py#L204-L211

Because torch will try to do this by default:
https://github.com/pytorch/pytorch/blob/v2.1.0-rc4/torch/distributed/fsdp/fully_sharded_data_parallel.py#L434-L441
https://github.com/pytorch/pytorch/blob/v2.1.0-rc4/torch/distributed/fsdp/_init_utils.py#L102-L111
https://github.com/pytorch/pytorch/blob/v2.1.0-rc4/torch/distributed/fsdp/_init_utils.py#L136-L155
Since it's passing a value instead of letting it default to `None`, it is probably falling into  https://github.com/pytorch/pytorch/blob/v2.1.0-rc4/torch/distributed/fsdp/_init_utils.py#L152-L155

**Comment by awaelchli** [comment]
@carmocca I'll test it unless you have already started?
