### ISSUE TITLE
automatic_optimization=False disables checkpoint saving

### ISSUE THREAD

**Issue by petargyurov** [Lightning-AI/lightning#18556]
### Bug description

Setting `automatic_optimization=False` disables automatic saving of checkpoints. I am not sure if this is intended and if it is, is it well documented? 

At the moment the docstring states:
> If set to ``False`` you are responsible for calling ``.backward()``, ``.step()``, ``.zero_grad()``.

### What version are you seeing the problem on?

v2.0

### How to reproduce the bug

```python
class MyModel(pl.LightningModule):
    def __init__(self, num_classes, bias):
        super().__init__()
        ...
        self.automatic_optimization = False
```

### Error messages and logs

No error messages. No folder is created for checkpoints and artifacts folder is empty.

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component: LightningModule
#- PyTorch Lightning Version: 2.0.8
#- PyTorch Version: 1.9.5
#- Python version: 3.10.6
#- OS: Mac OS Ventura 13.5.2
#- CUDA/cuDNN version: N/A
#- GPU models and configuration: N/A
#- How you installed Lightning: `pip`
#- Running environment of LightningApp: local
```

</details>

### More info

Adding the `ModelCheckpoint` callback does not help.

cc @awaelchli @borda

**Comment by awaelchli** [comment]
@petargyurov Yes it is intentional. If the step count does not increase from one time to the next, the checkpointing won't happen. This is to enable the use case when the user wants to skip steps or epochs intentionally (and not produce a useless checkpoint). 

Of course, just toggling `self.automatic_optimization = False` is not the intented use case. The user also needs to change their training step to call zero grad, backward, and (important!) step on the optimizer.

**Comment by awaelchli** [comment]
It might be possible to change this 
https://github.com/Lightning-AI/lightning/blob/ac576ffb8040ccd55c6ea5d130c03e9d4b2959b6/src/lightning/pytorch/callbacks/model_checkpoint.py#L387

to use the total batch idx instead of the global step. Then the user could in theory omit optimizer step calls but get checkpointing (not sure if that's meaingful?), but we would need to check if that has any undesired side effects.

**Comment by petargyurov** [comment]
> Of course, just toggling self.automatic_optimization = False is not the intented use case. The user also needs to change their training step to call zero grad, backward, and (important!) step on the optimizer.

I see, thanks for clarifying.

I toggled it to `False` because I am trying to implement UNet as a Lightning Module; however, I was running into this error:

```
File "/Users/me/.pyenv/versions/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
I wonder if there's anything else I could do in this case to avoid having to write the manual optimization?

---- 

Also, I implemented manual checkpoint saving using `on_validation_epoch_end` but is there any way to still leverage the `ModelCheckpoint` callback or am I forced to implement my own logic (e.g: monitoring `val_loss`, saving the last `k` checkpoints, etc) ?

**Comment by awaelchli** [comment]
Your Unet backbone is probably frozen. You need to set `requires_grad=True` on the parametes of your Unet if you want to train it. You can only call `.backward()` on a PyTorch graph that requires gradients.

**Comment by ZenGengChin** [comment]
I would suggest you change the code in ModelCheckpoint._should_skip_saving_checkpoint.

```{python}
    def _should_skip_saving_checkpoint(self, trainer: "pl.Trainer") -> bool:
        from lightning.pytorch.trainer.states import TrainerFn

        return (
            bool(trainer.fast_dev_run)  # disable checkpointing with fast_dev_run
            or trainer.state.fn != TrainerFn.FITTING  # don't save anything during non-fit
            or trainer.sanity_checking  # don't save anything during sanity check
            or self._last_global_step_saved == (trainer.current_epoch+1) *  trainer.num_training_batches   # already saved at the last step
        )
```
