### ISSUE TITLE
Troublesome recommendation on num_workers

### ISSUE THREAD

**Issue by stas00** [Lightning-AI/lightning#18723]
### Bug description

I struggle with this warning (multiplied 512 times on 512 gpus):

```
pytorch_lightning/trainer/connectors/data_connector.py:442: PossibleUserWarning: The dataloader, 
val_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of 
the `num_workers` argument` (try 48 which is the number of cpus on this machine) in the `DataLoader` 
init to improve performance.
```

It comes from here:

https://github.com/Lightning-AI/lightning/blob/09a0fb26d2bb819c6cbabf87c695b657ac5d305f/src/lightning/pytorch/trainer/connectors/data_connector.py#L439-L445

The warning doesn't take into account much of the user's situation and seemingly blindly compares num_workers of a single process to the total number of cpu-cores?

Questions:
1. why do you consider `num_workers == 2` to be insufficient - most serious LLM workloads use this settings for a perfect non-bottlenecked DL performance - if DL is slow preprocessing is usually needed, and not more workers.
2. why do you not take into account that there could be more than one process/gpu? At the very least use ncores/gpus to use the upper bound.
3. and even then this is a bad recommendation since if you give all cpu cores to DL workers how will the main process run? how will system processes run - this recommendation will lead to a worse outcome for the end user if they were to heed it, since now the real important processes will have to compete with DL workers for compute. So you really have `48 - 8 = 40` cpu-cores for gpus to start with (if the total is 48). And then you need a few more cores for the system processes. So more like 38.
4. and even if I only had a single process - allocating 48 DL workers is not a very helpful suggestion either

I think it'd be very difficult to have a one-fit-all recommendation heuristics, so perhaps it's best to remove it altogether and instead discuss various use cases and how to check if one's DL is a bottleneck for the compute in the documentation?

Thank you for reading.

cc @borda

**Comment by awaelchli** [comment]
Hey @stas00 

Does this one #18591 help?
If you want, we can think about incorporating the main process as well so that the total number of workers + main processes are no more than CPU cores available. I think it would be a reasonable improvement.

I don't think that the situation is as alarming as you word it. Most users familiar with PyTorch will know that they have to tune the num workers and that there is no golden formula. The warning is more for beginners or a reminder in case you foget.
While controversial, and not everyone agrees with it including me, the philosophy of lightning around performance has always been to warn about potential gaps, and false positives are considered acceptable. That's why the warnings are still there today. I recommend we gather more feedback from users around this topic.

**Comment by awaelchli** [comment]
> I struggle with this warning (multiplied 512 times on 512 gpus):

This definitely shouldn't happen. The warning should only be emitted on rank 0, not 512 times, because it's guarded by the rank check. Would you mind checking what is going on there? Is this running in the context of the torchrun + SLURM that you mentioned the other day? If so, I am surprised because torchrun would set the rank environment variable at minimum.

**Comment by stas00** [comment]
Hi Adrian,

> Does this one https://github.com/Lightning-AI/lightning/pull/18591 help?

Definitely, that's already a great improvement - thank you! 

and I left 2 possible suggestions in there.

>> I struggle with this warning (multiplied 512 times on 512 gpus):
> This definitely shouldn't happen. 

I screwed up. I was testing on a several nodes and got a handful of those, interleaved with a gazillion of other warnings and info lines, so I thought it would multiply once I'm ready to launch of 64 nodes.

But it proved to be that it warns for each dataset - so I had 3 and you're correct it's only warning on global rank 0 - each of those 3 times. I barked at the wrong tree :( My apologies. I'm just so exhausted with the losing fight of having a human-readable log file... so I end up doing blunders like this one :(

**Comment by awaelchli** [comment]
I'm happy to explore these refinements you suggested. 

No worries, then I'm glad it's not a bug. Are there any other warnings from lightning that contribute to the wall of logs you get that we should look at?

**Comment by stas00** [comment]
Thank you for asking, Adrian.

Let's look at this one:
```
[20:0]:[NeMo W 2023-10-06 19:20:58 nemo_logging:349] /exp/retro-llama/tr006-llama2-7b/CONDA_ENV_NAME/lib/python3.9/site-packages/pytorch_lightning/loops/training_epoch_loop.py:151: UserWarning: You're resuming from a checkpoint that ended before the epoch ended. This can cause unreliable results if further training is done. Consider using an end-of-epoch checkpoint
```
Many shared SLURM environments have a relatively short time limit to each job so one can't do one epoch w/o restart and resuming. e.g. some have only 20h top.

In "can cause unreliable results" are you perhaps implying that there is no guarantee the DL will not continue from where it left off on saving the last checkpoint but will repeat the same data? Shouldn't PTL save the worker RNG state and correctly restore it on resume. Though we custom DL there is no way PTL could easily do that.

But in general a 3 months training will take many restarts, not only because of a short SLURM job limit, but also because there will be divergences and rollbacks.

And yes the operator needs to be super-aware whether the resume breaks the unique flow of samples and leads to replacements.

**Comment by stas00** [comment]
This?
```
site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:212: UserWarning: You 
called `self.log('consumed_samples', ...)` in your `training_step` but the value needs to be floating 
point. Converting it to torch.float32.
```
how `consumed_samples` are a float, when it's an integer? you can't have 2.5 samples

**Comment by stas00** [comment]
In general, wrt we-try-to-guess-what-you-might-be-doing-wrong category of warnings:

There should be a way for an operator to say to some of these warnings - I know what I'm doing please do warn me about real problems, but this warning is on me.

If there is no such mechanism, the operator starts ignoring the warnings, because if someone forgot 5 "the floor is wet" signs on the street for a week, if later you add another one in the vicinity of the previous ones and when the floor is actually wet, this warning will be ignored because now they know the sign is false and some people will slip. 

It's the same but somewhat reversed principle of a broken window - if you don't fix it quickly, others will find a way to break more windows in the same building. But here the user has no way to fix the allegorical window, because it's not actually broken, yet the warning exists.

**Comment by stas00** [comment]
BTW, do DL workers always get killed when switching between train <-> eval <-> test?

If they aren't then you actually need to additionally divide by num_datasets to get the upper bound.

the math should then be:
```
upper bound = cpu-cores // num_gpus // num_datasets - 1
```

For quite some time I have been training w/o eval/test cycles, for a variety of reasons and performing eval via checkpoints in a separate job, so I am not sure what the current situation is.

**Comment by awaelchli** [comment]
https://github.com/Lightning-AI/lightning/pull/18737 and #18744 should hopefully address the main concerns in this issue. #18744 should be seen as a pain killer rather than a solution. It will suppress warnings of the category PossibleUserWarning, which might be false-positive. Real warnings of any other category (like these https://github.com/Lightning-AI/lightning/issues/18723#issuecomment-1751327450) will still show. 

For https://github.com/Lightning-AI/lightning/issues/18723#issuecomment-1751307472 I don't know what to do at this time. If you believe it's a high priority, we should start a separate discussion for this.

**Comment by stas00** [comment]
It has been awesome to be heard and you acting upon my requests so quickly, Adrian - thank you!

As you suggested I have forked off the remaining unaddressed warning into its own Issue:
https://github.com/Lightning-AI/lightning/issues/18780

**Comment by awaelchli** [comment]
Thanks for the positive feedback, Stas. I'm glad this was helpful.
