### ISSUE TITLE
LightningCLI logger related tests not being run in pull requests

### ISSUE THREAD

**Issue by mauvilsa** [Lightning-AI/lightning#18823]
### Bug description

It seems that the logger related unit tests for LightningCLI are not being run: https://github.com/Lightning-AI/lightning/blob/c68ff6482f97f388d6b0c37151fafc0fae789094/tests/tests_pytorch/test_cli.py#L1452-L1496

I am not sure what tests are run when. But this should be observed in any pytorch pull request. To me it is clear that the tests are skipped because incompatible changes were merged and 2.1 was released without anyone noticing that it is broken. I already released a new version of jsonargparse (4.26.0) to fix the issue. However, it might be convenient for the tests to be run to identify problems earlier.

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

cc @carmocca @borda

**Comment by awaelchli** [comment]
@mauvilsa These tests don't run in the CI because the dependencies don't get installed. This is intentional and only the case for a few tests. Installing all logger dependencies has caused issues in the past and is not something we have the bandwidth to maintain at the moment. For the time being, we guarded the few tests for which mocks aren't sufficient. 

To avoid regressions with your issue that you described, we can come up with a separate test so we don't need to rely on the 3rd party depencencies.

**Comment by Borda** [comment]
> @mauvilsa These tests don't run in the CI because the dependencies don't get installed. This is intentional and only the case for a few tests.
> To avoid regressions with your issue that you described, we can come up with a separate test so we don't need to rely on the 3rd party depencencies.

I still believe that we shall have these covered in CI as some integration cases but non blocking to regular development / PRs
