### ISSUE TITLE
fabric.save errors when checkpoint exists; introduce a override_checkpoint=True argument

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lightning#18873]
### Description & Motivation

Imagine you did a fast debugging run and everything is fine. Then you are training a model for many hours and then it fails because you forgot to delete the checkpoint file:

```python
FileExistsError: The checkpoint directory already exists and is not empty: 
```

It would be nice to introduce `override_checkpoint` setting or so. E.g.,

```python
fabric.save("model_iter_best.ckpt", state, override_checkpoint=True)
```

cc @borda @tchaton @justusschock @awaelchli @carmocca

**Comment by awaelchli** [comment]
Hi
I made a counter proposal in https://github.com/Lightning-AI/lightning/issues/18873 (see PR description). I'd like to avoid overloading the `fabric.save()` method to become a checkpoint orchestration, and keep it as atomic as possible to enable easier adoption when switching from `torch.save()` to it. Since `torch.save()` overwrites the file, it should be relatively natural to assume that `fabric.save()` also does that and so I don't see a need to introduce a new argument. The naming of checkpoints, testing for existence etc. should ideally be implemented by the user. This is the kind of control where Fabric offers the flexibility for those who want it.

The PR extends the error checking so that we only error when the user is really trying to do a bad thing that could lead to data loss. In the other cases, when we are confident that the underlying folder is a checkpoint, we can overwrite it.

**Comment by rasbt** [comment]
@awaelchli Oh perfect, I think overriding it by default like `torch.save` is even better. 
(I mainly only suggested `override_checkpoint` because I thought that the current design was intentional to avoid accidental deletion)
