### ISSUE TITLE
Revisit CONTRIBUTING.md

### ISSUE THREAD

**Issue by camruta** [Lightning-AI/lightning#6622]
## 📚 Documentation

Update [CONTRIBUTING.md](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md) to include detailed steps and missing guidelines Pytorch-Lightning developer machine setup. The setup instructions are currently under "[Testing](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md#testing)" section, and they don't have information about all the necessary dependencies. We should rename the section to make it easy for developers to find it, add missing steps, as well as add debugging/testing/troubleshooting guidelines.

A good example to follow is [Pytorch CONTRIBUTING.md](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#developing-pytorch).

Some of the missing steps I and my colleagues learned while setting up Pytorch-Lightning for development on local machine:
1. Install dependencies from requirements.txt (I am new to OSS development, and didn't run "pip install -r requirements.txt", directly went to "[Testing](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md#testing)" instructions and ran commands from there, resulting into later having to install bunch of dependencies manually after running "make test" and getting bunch of test failures).
2. brew install cmake
3. brew install libuv
4. brew install pkg-config
5. After the setup, I still ran into errors, and had to manually install torch.

**Comment by kaushikb11** [comment]
Hey @camruta! Thanks for opening the Issue. We are always looking to improve the docs for our Users.
You could run `pip install -e .` or `python setup.py install` to install it from the source, it handles the requirements required.
We are happy to add the block of suggestions you mentioned. Feel free to open a PR, will be happy to help you in the process! :)

**Comment by Borda** [comment]
@camruta would it be useful for you rather use docker image with Ubuntu where all you mentioned is already ready...?

**Comment by kaushikb11** [comment]
@camruta Any update on this?

**Comment by camruta** [comment]
I'll reopen and try to work on it this week.

**Comment by carmocca** [comment]
Will use this issue to address a broader revisit to the file, no limited to the installation steps.

**Comment by ekagra-ranjan** [comment]
Hi!

The Cherry-picking way section of [How to fix PR with mixed base and target branches?](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md#how-to-fix-pr-with-mixed-base-and-target-branches) in CONTRIBUTING.md suggests to:
1. Checkout to `my-branch`
2. Create a new branch called `my-branch-backup` and then move into that branch
3. Do a reset hard on the new parent branch
4. Cherry-pick last commits from `my-branch-backup` 
5. Do a forced push

Step 2 creates a backup branch and switches into it. Step 3 will bring `my-branch-backup` in parity with the new parent branch but then all the new commits of the user in `my-branch-backup` will be erased. Shouldn't Step 4 therefore fail as we won't be able to cherry-pick from `my-branch-backup` since we reset that branch?

I believe Step 2 should be changed from `git checkout -b my-branch-backup` to `git branch my-branch-backup` so that the user can stay in `my-branch` and update it without raising a new PR in case `my-branch` was already in review.

**Comment by carmocca** [comment]
Go for it @ekagra-ranjan!
