### ISSUE TITLE
Make tensorboard into an pip extra

### ISSUE THREAD

**Issue by slimshreydy** [Lightning-AI/lightning#9900]
Pytorch lightning provides a pretty convenient abstraction for writing training loops, but the tensorboard dependency ends up dramatically increasing the scope and footprint of the library. As a result, if we import pytorch-lightning into our own packages, it dramatically increases the footprint of those libraries too.

Tensorboard usage feels fairly optional for the pytorch-lightning experience, but it's listed as an unconditional dependency in the requirements.txt file. Would it be possible to move tensorboard into the pip extras instead? Seems like y'all already do this for other visualization and logging tools like `wandb`.

cc @borda @tchaton @awaelchli @edward-io @rohitgr7

**Comment by rohitgr7** [comment]
from the internal discussion, we are thinking keep `logger=True` (by default) and use:
- CSVLogger (if tensorboard is not installed)
- TensorboardLogger (if tensorboard is installed)

and remove tensorboard from `requirements.txt`.

thoughts cc @PyTorchLightning/contributors

**Comment by schmitts** [comment]
> from the internal discussion, we are thinking keep `logger=True` (by default) and use:
> 
>     * CSVLogger (if tensorboard is not installed)
> 
>     * TensorboardLogger (if tensorboard is installed)
> 
> 
> and remove tensorboard from `requirements.txt`.
> 
> thoughts cc @PyTorchLightning/contributors

I would very much prefer an explicit option. Automagic matching based on installed stuff is brittle and makes packaging, e.g., for https://spack.io/, harder.

**Comment by williamFalcon** [comment]
@slimshreydy do you have benchmarks either in terms of memory/disk space/install time that would be gain from this? there’s already a slim install version of lightning for production use…

**Comment by JacobHayes** [comment]
Aside from memory/disk/install time concerns (I admittedly haven't looked at this), the `tensorboard` dependency causes a lot of conflicts for me when locking packages, particularly their `protobuf` pins. For example, `pipenv` took 4 hours to _fail_ with unresolvable dependencies, but pinning `tensorboard` and `protobuf` manually allowed it to resolve in 2 minutes.

This isn't _directly_ your problem of course, but is something I and ~3 other folks at my company have fought with a number of times over the last few months (particularly because without knowing to pin things, relocking would take forever to even fail). There are a [couple](https://github.com/Lightning-AI/lightning/issues/4332#issuecomment-1245133128) [other](https://github.com/Lightning-AI/lightning/issues/4332#issuecomment-1269860968) comments on #4332 mentioning similar conflicts.

**Comment by sustr-equi** [comment]
I second with @JacobHayes 

> there’s already a slim install version of lightning for production use

What version is that? I didn't find a mention of it in docs, and there is no such "extras" package:
```
In [1]: import importlib_metadata

In [2]: importlib_metadata.metadata('pytorch-lightning').get_all('Provides-Extra')
Out[2]: ['all', 'cpu', 'cpu-extra', 'dev', 'examples', 'extra', 'loggers', 'test']
```

If there was `pytorch-lightning[slim]` or `pytorch-lightning[core]` that would be great! If it makes sense to the maintainers I can create a PR which adds this option.

**Comment by JacobHayes** [comment]
I might be (happily) wrong, but I didn't think there's a way for extras to _remove_ a declared dependency.

**Comment by carmocca** [comment]
For internal employees, this was discussed [here](https://www.notion.so/lightningai/Community-proposal-make-TensorBoard-optional-1298187756ec4a62a85c52ae472ac34b). Still pending resolution.

**Comment by sustr-equi** [comment]
Hi @carmocca any update on this? As I said, if it makes sense to the maintainers I can create a PR which adds this option. Thank you for info :)

**Comment by carmocca** [comment]
You can work on making sure PL works with `tensorboard` uninstalled, by gating imports as necessary.

But there's still no final decision on whether yo remove it from requirements.

**Comment by sustr-equi** [comment]
Hi @carmocca has a final decision on whether to remove it from requirements been made? 

Unfortunately only removing `tensorboard` from imports seems not enough, particularly because the `protobuf` dependency is transitively installed from `tensorboard`. `protobuf` is famously problematic -- this is because many open source libraries outside of google that do not live in their internal monorepo have to list which versions they are not compatible with. Google manages this because they have many tests in the monorepo and can safely fix everything, but outside of google everything breaks all the time.

**Comment by carmocca** [comment]
I understand! That's definitely a valid "pro" for removing it. Unfortunately, the decision is not in my hands. Still pending

**Comment by mniyas** [comment]
Is there any good work around for this problem? I'm trying to install PL and `google-cloud-pubsub` which is causing a dependency conflict due to `protobuf` versions.

**Comment by carmocca** [comment]
After long deliberation, we've decided to demote the `TensorBoardLogger` as the default logger so that we can remove the `tensorboard` dependency from the base requirements. This also has the implication that `Trainer(logger=False|True)` will be deprecated in favor of passing the logger you choose: `Trainer(logger=ALogger())`.

The plan is to remove the requirement in 1.9 with a deprecation cycle where we install `tensorboard` programmatically for those still passing `logger=True` or `logger=TensorBoardLogger()`. Then in v2.0.0 (no ETA currently) we will remove this compatibility layer.

If you have any other suggestions or questions, feel free to ask here. You can also review the PR (WIP atm) open in #15562.

Thank you all!

**Comment by vadimkantorov** [comment]
There's another problem with importing torch.utils.tensorboard / tensorboard unconditionally: currently there's a nasty bug in tensorboard that throws on import (ergo on lightning import), if a recent protobuf is installed. And this happens even if tensorboard logging functionality isn't used. In the meanwhile we're waiting for safe import fixes from pytorch / tensorboard (waits on tensorflow fixes), it might be a good idea to also add a guard in lightning that will guard these imports and prevent an exception at import time.

More context and links: https://github.com/pytorch/pytorch/issues/90374

**Comment by williamFalcon** [comment]
we solved this issue in 1.8.4.

**Comment by vadimkantorov** [comment]
> We will further make this dependency smaller until we get to 2.0

Not completely following what means "make dependency smaller". Is the issue "PL will still try to import torch.utils.tensorboard even if TensorBoardLogger isn't used" solved since 1.8.4?

Thanks!

**Comment by williamFalcon** [comment]
as of 1.8.4 we don’t import torch.utils.tensorboard we use a different package that has fewer issues. in 2.0 we are looking at ways of making it fully optional. 

we don’t yet have that finalized, so not sure what it will look like. but our goal for 2.0 is to remove the optional dependencies altogether

**Comment by vadimkantorov** [comment]
Also please free to add your thoughts to https://github.com/pytorch/pytorch/issues/90374

**Comment by carmocca** [comment]
To be precise, in v1.8.4 (PR #15728), we changed the default dependency from `tensorboard` to `tensorboardX` which should avoid the protobuf issues.

However, this still unconditionally imports `tensorboardX`. This is avoided in master (PR https://github.com/Lightning-AI/lightning/pull/15762) which hasn't been cherry-picked into a bugfix release. If you still have issues with importing `tensorboardX`, we can include it.

**Comment by manuelli** [comment]
It seems that `tensorboardX` still has the restrictive protobuf dependency, see [here](https://github.com/lanpa/tensorboardX/blob/master/setup.py#L44-L47). In particular it requires `'protobuf>=3.8.0,<=3.20.1'` which makes `pl` incompatible with many modern google libraries (e.g. `firebase-admin`) which wants a newer `protobuf` version. Is it on the roadmap to make the `tensorboardX` dependency optional for `pl`?

**Comment by vadimkantorov** [comment]
making completely optional tensorboard/tensorboardX and guard imports is probably the only way to go...

**Comment by vadimkantorov** [comment]
It appears that tensorboardX also has problems with protobuf. So waiting until PL drops tensorboard as required dependency: https://github.com/Lightning-AI/lightning/issues/9900#issuecomment-1366717227

**Comment by Borda** [comment]
@lantiga how about setting the default logger to CSV? :chipmunk:

**Comment by lantiga** [comment]
So this one is tricky because we don't want to change the default behavior silently (if you assume you'll have TensorBoard logs generated after a run and you find CSV logs unless you change your code, that will be pretty frustrating).

My proposal for the next release:
* keep TensorBoard as the default logger, so if you don't specify any logger you'll still go with TensorBoard, BUT
* move the tensorboardX dependency to extras
* produce a nice error message explaining that we moved tensorboard to extras and why, and just `pip install lightning[extras]` (or `pip install tensorboardx` or `pip install tensorboard`) to get it

This has a few advantages:
* it doesn't break existing environments upgrading to the latest version (in case they are using the default logger), because these will have tensorboardx or tensorboard already installed
* it fails loudly and immediately for people starting from new environments, with a clear call to action (install extras)
* it solves the problem with conflicting protobuf dependencies
* it is a non-breaking path towards eventually installing lazily in the future

**Comment by carmocca** [comment]
@lantiga How do you reconciliate that with our `Trainer(logger=True)` default? (`True` meaning use `TensorBoardLogger`). Any new installation that doesn't modify this flag (`None` or another logger) will fail immediately which I suspect will be a large percentage of users. This can get annoying.

This was my motivation for my comment https://github.com/Lightning-AI/lightning/issues/9900#issuecomment-1312551323

**Comment by lantiga** [comment]
I agree it can get annoying.

I'm worrying about `logger=True` suddenly starting to log to a CSV even for users having tensorboard installed is a more silent failure that requires code a code change to be fixed.

If we have a good way to install it programmatically and we can fast track it I'm all for it, we already had a prototype a couple of months ago.

The only alternative I see, that is kind of an in-between solution, is making `logger=True` fall back to CSV, but only if Tensorboard is not available.

**Comment by JacobHayes** [comment]
Looks like this can be closed now that https://github.com/Lightning-AI/lightning/pull/16349 has been released in 1.9.0! Thank you all so much for the work to deal with these annoying dependency conflicts

**Comment by vadimkantorov** [comment]
So is tensorboardX now a must for tensorboard logging? Or tensorboard package + torch.utils.data is also tried?

**Comment by carmocca** [comment]
We pick whichever is available, prefering `tensorboard`
